### ISSUE TITLE
Missing dependency for LMBD

### ISSUE THREAD

**Issue by ncclementi** [dask/zict#49]
When running the test suite I notice that if one were to use the `LMBD` class you need to have `lmbd` installed. See https://github.com/dask/zict/blob/b760997b98aad9aca8ab37fc4e8b5bb06809283d/zict/lmdb.py#L31-L32

Should we add this dependency to the requirements?

**Comment by jrbourbeau** [comment]
Thanks for reporting @ncclementi. Since `lmdb` is only required for the `LMBD` mapping (similar to how `pandas` is only required for the `dask.dataframe` API), we could instead add a `pytest.importorskip` call to the top of `zict/tests/test_lmdb.py`. That way all `lmdb`-related tests will be skipped if the `lmdb` package isn't installed
